services:
  transformers:
    build: ./
    env_file: transformers.env
    environment:
      - HF_HOME=/var/lib/hf_cache
    network_mode: bridge
    ports:
      - "5000:5000"
    volumes:
      - type: volume
        source: hf_cache
        target: /var/lib/hf_cache
    devices:
      - nvidia.com/gpu=all
volumes:
  hf_cache:
    external: true
